import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import Nav from '@/components/nav/nav'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  	  <Nav/>
        {children}
         <footer className="bg-gray-800 text-white py-4 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row justify-between items-center space-y-2 md:space-y-0">
          {/* Logo/Brand */}
          <div className="text-yellow-400 font-bold text-lg md:text-xl">FOOD</div>

          {/* Center Link */}
          <div className="text-sm md:text-base text-gray-300 hover:text-white transition-colors cursor-pointer">
            Политика конфиденциальности
          </div>

          {/* Right Text */}
          <div className="text-sm md:text-base text-gray-300">Проект и стил</div>
        </div>
      </div>
    </footer>
      </body>
    </html>
  );
}
